name: project-api
env: test
port: 8081
debugLevel:
  debug: 1
  info: 1
  error: 1
redis:
  username:
  addr: 10.xx.xx.xx:xx
  password:
mysql:
  uri: "username:password@tcp(xx.xx.xx.xx:xx)/db_name?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true"
